### PR TITLE
 LRAC-5492 Update connector so custom fields include field types

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://issues.liferay.com/browse/LRAC-5492

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:test:sf

**Comment by shinnlok** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by shinnlok** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/86761

**Pull request closed without merging**
