### PR TITLE
LRAC-6848 Always clears configurations on disconnect

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://issues.liferay.com/browse/LRAC-6848

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:forward

**Comment by shinnlok** [comment]
ci:retest

**Comment by rachaelkoestartyo** [comment]
hope rebasing would fix it

**Comment by rachaelkoestartyo** [comment]
ci:forward

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/96399

**Pull request closed without merging**
