### PR TITLE
[TECH-SUPPORT] LPS-53349 Scheduled LDAP import doesn't work as expected

### PR DESCRIPTION
**Pull request by laszlocsontos**
Hi Shinn,

Norbert has found issues with LPS-51676. Instead of relying on the lastImportTime, we now extended the scope of the global lock protecting the import process.

Please let us know about your thoughts.

Thanks,
László

/cc: @NorbertKocsis

### CODE REVIEW

**Comment by shinnlok** [comment]
Wouldn't the original problem potentially occur? If the startup import lock is released before the first scheduled import, we're going to be importing on "startup" twice again.

**Comment by shinnlok** [comment]
And this changes the behavior of importUsers(long companyId). It can be called (directly) by multiple threads and spawn off multiple problematic tasks.

**Comment by NorbertKocsis** [comment]
Hi,

The original problem is it didn't happen at all because the scheduled import always misfires at first time, so it won't happen twice.

"And this changes the behavior of importUsers(long companyId). It can be called (directly) by multiple threads and spawn off multiple problematic tasks."
It can already be done, all you need is to call it with different companies. (see LPS description Scenario 2) But we never call it directly except for the company init.

**Comment by shinnlok** [comment]
I'm talking about:

https://issues.liferay.com/browse/LPS-30527

**Pull request closed without merging**
