### PR TITLE
LRAC-5579 feature flag properties

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://issues.liferay.com/browse/LRAC-5579

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by shinnlok** [comment]
ci:forward

**Comment by rachaelkoestartyo** [comment]
ci:forward

**Comment by shinnlok** [comment]
ci:forward

**Comment by jpince** [comment]
@shinnlok please add liferay-continuous-integration as a collaborator to your repo https://grow.liferay.com/people/Pull+Request+Tester+for+Liferay+Developers

If you do this before the tests complete, I think it should automatically forward.

**Comment by shinnlok** [comment]
I've had it:

Screen Shot 2020-03-30 at 3 22 46 PM

**Pull request closed without merging**
