### PR TITLE
[TS]  LPS-132244 Add additional fallback mechanism to try to generate a non null liferayAnalyticsProjectId.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@shinnlok could you please take a look. See LPP-41425 for additional information.

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by shinnlok** [comment]
ci:forward

**Comment by shinnlok** [comment]
thanks @marianoalvarosaiz!

**Pull request closed without merging**
