### PR TITLE
LPS-64667

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by shinnlok** [comment]
Sorry just got back from a couple weeks of jury duty and noticed this. Why is this upgrade in 6.2.0? Since it's already released shouldn't we have it in 7.0.0 or be a Verify*?

**Comment by zxdgoal** [comment]
Hey @shinnlok 

Sorry, just got time to look at this issue again.

The reason why I put the fix in 6.2.0 is because in 6.1.x, the table of Layout does not have a row of ``userId``, so the layout table itself cannot decide who is the owner/creator of a layout.

Then when upgrading to 6.2.0, rows called userId and username is added there. However, when migrating Layout table from 6.1.0 to 6.2.0, these two rows are filled with default values since they do not exist in Layout table in 6.1.0.

So we only need to a logic specially for upgrading from 6.1 to 6.2 to fill rows of userId and username with correct values( we get them from resourcePermission table). 

As for 7.0.0 or  a VerifyProcess, since after 6.2 the Layout table already contains userId and username rows, we do not need the fix any more(  userId and username contains correct values)

Does that make sense to you ?

Thanks
John.

**Comment by shinnlok** [comment]
Hi @zxdgoal,
From your description, it should still be a VerifyProcess.

**Comment by zxdgoal** [comment]
Ok, let me try to  move the fix there.

Thanks

**Comment by zxdgoal** [comment]
Hey @shinnlok 

As this pr was committed, weeks ago I might forget some important thought when I writing the codes.

Another major reason I put the fix in upgrade is that:

In verifyResourcePermission.java we have a method called verifyLayout.

Its logic is filling correct resource permission for layouts model according its userId and username.

That is Layout table decides resource permission table. 

But this fix is making resource permission table decides Layout table's userId and username

Go back to our issue.

We know that due to Layout in 6.1.x is incomplete to 6.2.x (userId and username does not exists in 6.1.x), we should not apply verifyLayout method from verifyResourcePermission.java because it will use default  userId and username from layoutTable to verify.

We have to fill in correct userId and username for Layout table BEFORE verifyLayout method from verifyResourcePermission.java is called in verify process.

I can see the issue is a bit confused.

I hope I made myself clear.

Thanks
John.

**Comment by shinnlok** [comment]
@zxdgoal 
Since VerifyResourcePermission#verifyLayout is only adding/modifying permissions that didn't previously exist for layouts, I don't see why your code would be a problem? If the permission didn't exist, where else would you grab the userId from?

**Comment by zxdgoal** [comment]
@shinnlok 

>Since VerifyResourcePermission#verifyLayout is only adding/modifying permissions that didn't previously exist for layouts, I don't see why your code would be a problem?

Here point is the order of VerifyResourcePermissions and VerifyLayout.

The VerifyLayout has to be prior to VerifyResourcePermissions;Otherwise, it will change the userId of a layout ownerpermission to default user Id .

I checked the verify order in VerifyProcessSuite.java.

VerifyLayout is prior to VerifyResourcePermissions so moving the fix in VerifyLayout will still fix the issue.

However, I am a bit confused that by doing this. we will have two contradicted verify processes.

Think over this scenario:
In Layout table a layout's userId is 1, and in resourcePermission table, somehow, the userId of ownerPermission for this layout is 2. Now we start verify process.

Before adding my fix in VerifyLayout, the VerifyResourcePermission#verifyLayout will change the userId from 2 to 1 in 
resourcePermission table as I said Layout userId decides resourcePermission userId.

But after adding my fix in VerifyLayout, because VerifyLayout is prior to VerifyResourcePermission, it will change Layout userId form 1 to 2, as my fix logic is resourcePermission userId decides Layout userId.

You can see my fix breaks here.

I would say, to be inconsistent, we should always make Layout userId decides resourcePermission userId and only in rare situation, e.g. upgrading from 6.1 to 6.2, we need to use the reverse as we know Layout table is not filled with correct userIds.

Thanks
John.

**Comment by shinnlok** [comment]
I'm still confused..

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/verify/VerifyResourcePermissions.java#L99-100

Doesn't this mean that no permissions existed for the layout prior to the Verify? Therefore..

> In Layout table a layout's userId is 1, and in resourcePermission table, somehow, the userId of ownerPermission for this layout is 2. Now we start verify process.

Shouldn't occur?

**Comment by shinnlok** [comment]
If I'm mistaken, either the logic in that verify is wrong or yours is. In other words.. if what you are saying is true, there is no way to "recover" and fix your issue after someone has already upgraded and starts up 6.2. Can you go over this with @hhuijser or someone local. This way we can get it resolved faster without the time zone difference.

Thanks.

**Comment by zxdgoal** [comment]
>There is no way to "recover" and fix your issue after someone has already upgraded and starts up 6.2.

Yes, it is.

**Comment by zxdgoal** [comment]
> Doesn't this mean that no permissions existed for the layout prior to the Verify? Therefore..
In Layout table a layout's userId is 1, and in resourcePermission table, somehow, the userId of ownerPermission for this layout is 2. Now we start verify process.
Shouldn't occur?

Sorry, I made a mistake here. I debug again, finding the method which changes layout userId, e.g. verifyResourcedModel method,  is not called from verifyLayout method, but from https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/verify/VerifyResourcePermissions.java#L237

**Pull request closed without merging**
