### PR TITLE
LRAC-4843 Update configurations and preferences when selected Group, UserGroup or Organization is deleted

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://issues.liferay.com/browse/LRAC-4843

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
added commits

**Comment by rachaelkoestartyo** [comment]
fixed https://github.com/brianchandotcom/liferay-portal/pull/83067
missing petra-string dependencies for StringPool

**Comment by shinnlok** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/83070

**Comment by rachaelkoestartyo** [comment]
accidentally updated my branch so the pull was closed.. i resent it directly https://github.com/brianchandotcom/liferay-portal/pull/83144

**Pull request closed without merging**
